d={"name":"anu","age":24,"place":"calicut",}
d.clear()
print(d)
d={"name":"anu","age":24,"place":"calicut",}
d.pop("place")
print(d)
d={"name":"anu","age":24,"place":"calicut",}
d.popitem()
print(d)
d={"name":"anu","age":24,"place":"calicut",}
print(d.get("name"))
d={"name":"anu","age":24,"place":"calicut",}
print(d.values())
d={"name":"anu","age":24,"place":"calicut",}
print(d.items())
d={"name":"anu","age":24,"place":"calicut",}
print(d.keys())
d={"name":"anu","age":24,"place":"calicut",}
d.update({"mark":74})
print(d)
d={"name":"anu","age":24,"place":"calicut",}
d.setdefault("place")
print(d)
d={"name":"anu","age":24,"place":"calicut",}
l=[1,2,21,3,4,5]
print(d.fromkeys(l))

