a=10
b=20  
c=35
print(a,b,c)
a=36.3
b=48.5
print(a,b)
name="akil"
print(name)
name='akeel'
print(name)
name=["anu","anas","sanu"]
print(name)
name=("hashir","ammu","azar")
print(name)
name={"ayush","shan"}
print(name)
std={'rollno':10,'name':'mesi','age':22}
print(std)