import re
a="welcome TO ALL 2005"
print(re.sub("w","W",a))
print(re.sub("e","E",a))
print(re.split("e",a))
print(re.findall("e",a))
print(re.findall("g",a))
print(re.search("e",a))
print(re.search("[abcd]",a))
print(re.search('a.',a))
print(re.search('e.',a))
print(re.search('w..',a))
print(re.search("w.*",a)) 
print(re.search("c.*",a))
print(re.search("l.+",a))
print(re.search("m.+",a))
print(re.search("c.?",a))
print(re.search('[w][e]',a))
print(re.search('[w].*[e]',a))
print(re.search("[a-z]",a))
print(re.search("[A-T]",a))
print(re.search("[2-5]",a))
print(re.search('[a-z].{4}',a))
print(re.search('[a-z].{7}',a))
              