a="   welcome             "
print(a.capitalize())
print(a.center(50))
print(a.count("e"))
print(a.endswith("e"))
print(a.endswith("m"))
print(a.find("o"))
print(a.find("f"))
print(a.index("e"))
b="{} to all"
print(b.format(a))
print(a.isalnum())
print(a.isdigit())
print(a.islower())
print(a.split())
print(a.strip( ))
print(a.lstrip())
print(a.rstrip())
print(a.startswith("m"))
print(a.upper())