f=open("pythonhub/filehandling/new.txt",'x')
f.write("welcome")
f=open("pythonhub/filehandling/new.txt",'w')
f.write("to all")

f=open('new.txt','w')
f.write('welcome')
f.write('new contet')
f.write('hello'+'welcome')
f.write(str(120))

f=open('new.txt',"a")
f.write("welcme")
f.write("hello"+"welcome")
f.write(str(120))

f=open("new.txt","r")
print(f.read(10))
f.seek(0)
print(f.read())
print(f.readline())
print(f.readlines)